export const ApiErrorCodes = {
  GENERIC: 'GENERIC',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  AUTH_FAILED: 'AUTH_FAILED',
  BEARER_TOKEN_MISSING: 'AUTH_BEARER_TOKEN_MISSING',
  BEARER_SCHEME_INVALID: 'AUTH_BEARER_SCHEME_INVALID',
  BEARER_TOKEN_EMPTY: 'AUTH_BEARER_TOKEN_EMPTY',
  BEARER_TOKEN_INVALID: 'AUTH_BEARER_TOKEN_INVALID',
  BEARER_PROCESSING_FAILED: 'AUTH_BEARER_PROCESSING_FAILED',
  BEARER_UNEXPECTED_ERROR: 'AUTH_BEARER_UNEXPECTED_ERROR',
  BASIC_HEADER_MISSING: 'BASIC_HEADER_MISSING',
  BASIC_SCHEME_INVALID: 'BASIC_SCHEME_INVALID',
  BASIC_HEADER_EMPTY: 'BASIC_HEADER_EMPTY',
  BASIC_CREDENTIALS_INVALID: 'BASIC_CREDENTIALS_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
} as const

export const EntityNotFoundErrorCodes = {
  GENERIC: 'GENERIC',
} as const

export const DomainErrorCodes = {
  GENERIC: 'GENERIC',
} as const

export const CoreErrorCodes = {
  GENERIC: 'GENERIC',
} as const
