import { z } from 'zod'

export const SF_STD_AccountSchema = z.object({
  attributes: z
    .object({
      type: z.literal('Account'),
      url: z.string().nullish(),
    })
    .nullish(),
  Id: z.string().nullish(),
  IsDeleted: z.boolean().nullish(),
  MasterRecordId: z.string().nullish(),
  Name: z.string().nullish(),
  Type: z.string().nullish(),
  ParentId: z.string().nullish(),
  BillingStreet: z.string().nullish(),
  BillingCity: z.string().nullish(),
  BillingState: z.string().nullish(),
  BillingPostalCode: z.string().nullish(),
  BillingCountry: z.string().nullish(),
  BillingStateCode: z.string().nullish(),
  BillingCountryCode: z.string().nullish(),
  BillingLatitude: z.number().nullish(),
  BillingLongitude: z.number().nullish(),
  BillingGeocodeAccuracy: z.string().nullish(),
  ShippingStreet: z.string().nullish(),
  ShippingCity: z.string().nullish(),
  ShippingState: z.string().nullish(),
  ShippingPostalCode: z.string().nullish(),
  ShippingCountry: z.string().nullish(),
  ShippingStateCode: z.string().nullish(),
  ShippingCountryCode: z.string().nullish(),
  ShippingLatitude: z.number().nullish(),
  ShippingLongitude: z.number().nullish(),
  ShippingGeocodeAccuracy: z.string().nullish(),
  Phone: z.string().nullish(),
  Fax: z.string().nullish(),
  AccountNumber: z.string().nullish(),
  Website: z.string().nullish(),
  PhotoUrl: z.string().nullish(),
  Sic: z.string().nullish(),
  Industry: z.string().nullish(),
  AnnualRevenue: z.number().nullish(),
  NumberOfEmployees: z.number().nullish(),
  Ownership: z.string().nullish(),
  TickerSymbol: z.string().nullish(),
  Description: z.string().nullish(),
  Rating: z.string().nullish(),
  Site: z.string().nullish(),
  OwnerId: z.string().nullish(),
  CreatedDate: z.string().nullish(),
  CreatedById: z.string().nullish(),
  LastModifiedDate: z.date().nullish(),
  LastModifiedById: z.string().nullish(),
  SystemModstamp: z.string().nullish(),
  LastActivityDate: z.string().nullish(),
  LastViewedDate: z.string().nullish(),
  LastReferencedDate: z.string().nullish(),
  Jigsaw: z.string().nullish(),
  JigsawCompanyId: z.string().nullish(),
  AccountSource: z.string().nullish(),
  SicDesc: z.string().nullish(),
})
export type SF_STD_AccountSchema = z.infer<typeof SF_STD_AccountSchema>
